debug: false

spring:
    main:
        allow-bean-definition-overriding: true
    mvc:
        servlet:
            path: /
        static-path-pattern: /**
        view:
            prefix: /webpage/
            suffix: .jsp
    profiles:
        active: dev
    redis:
        database: 0
        host: 127.0.0.1
        password: 123456
    resources:
        static-locations: /**
minidao:
    base-package: org.jeecgframework.*,com.jeecg.*
    db-type: mysql
    show-sql: true
